# Generated by Django 4.1 on 2024-04-15 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('name_user', models.CharField(default='', max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.FloatField(default=1)),
                ('tamanio', models.FloatField(blank=True, default=0)),
                ('libraje', models.FloatField(blank=True, default=0)),
                ('conexion', models.CharField(blank=True, max_length=10)),
                ('unidad_medida', models.CharField(default='', max_length=100, null=True)),
                ('conexion_medida', models.CharField(blank=True, max_length=10)),
                ('codigo', models.CharField(max_length=20, null=True)),
                ('no_serie', models.CharField(blank=True, max_length=10)),
                ('no_serie_interno', models.CharField(blank=True, max_length=10)),
                ('orden_compra', models.CharField(blank=True, max_length=10)),
                ('tipo_orden_compra', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(blank=True, max_length=40)),
                ('pozo', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('modelo', models.CharField(blank=True, default='', max_length=100)),
                ('marca', models.CharField(blank=True, default='', max_length=100)),
                ('area', models.CharField(blank=True, default='', max_length=100)),
                ('proyecto', models.CharField(blank=True, default='', max_length=200)),
                ('resguardo', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('categoria', models.CharField(blank=True, max_length=15)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('folio', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Renta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=0)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('fecha_regreso', models.DateField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.proveedor'),
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('renta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.renta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.venta')),
            ],
        ),
    ]
