# Generated by Django 4.1 on 2024-05-27 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('name_user', models.CharField(default='', max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Estados_de_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_disponible', models.FloatField()),
                ('estado', models.CharField(max_length=100)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('condiciones', models.TextField(default='')),
            ],
            options={
                'db_table': 'estados_producto',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('folio', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.FloatField(default=1)),
                ('tamanio', models.CharField(blank=True, default=0, max_length=20)),
                ('libraje', models.FloatField(blank=True, default=0)),
                ('conexion', models.CharField(blank=True, max_length=10)),
                ('unidad_medida', models.CharField(default='', max_length=100, null=True)),
                ('conexion_medida', models.CharField(blank=True, max_length=10)),
                ('codigo', models.CharField(max_length=20, null=True)),
                ('no_serie', models.CharField(blank=True, max_length=50)),
                ('no_serie_interno', models.CharField(blank=True, max_length=50)),
                ('orden_compra', models.CharField(blank=True, max_length=200)),
                ('tipo_orden_compra', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(blank=True, max_length=40)),
                ('pozo', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('modelo', models.CharField(blank=True, default='', max_length=100)),
                ('marca', models.CharField(blank=True, default='', max_length=100)),
                ('area', models.CharField(blank=True, default='', max_length=100)),
                ('proyecto', models.CharField(blank=True, default='', max_length=200)),
                ('resguardo', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('categoria', models.CharField(blank=True, max_length=15)),
                ('disponible', models.BooleanField(default=True)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.proveedor')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(max_length=50)),
                ('cantidad', models.FloatField()),
                ('fecha_salida', models.DateField()),
                ('echa_regreso', models.DateField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estados_de_producto')),
            ],
            options={
                'db_table': 'movimientos',
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('movimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.movimiento')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.producto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historial',
            },
        ),
        migrations.AddField(
            model_name='estados_de_producto',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.producto'),
        ),
    ]
