# Generated by Django 4.1.7 on 2023-10-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycustomuser',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
