# Generated by Django 4.1 on 2024-05-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_movimiento_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='estado',
            field=models.CharField(default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha_regreso',
            field=models.DateField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha_salida',
            field=models.DateField(default='', null=True),
        ),
    ]
