# Generated by Django 4.1.7 on 2023-11-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_producto_proveedor_venta_renta_producto_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='proyecto',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
