# Generated by Django 4.1 on 2024-05-15 20:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_producto_tamanio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto_uso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_uso', models.FloatField(blank=True, default=0)),
                ('fecha_uso', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('estado', models.CharField(blank=True, default='Listo', max_length=30)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
            ],
            options={
                'db_table': 'Producto_uso',
            },
        ),
    ]
