# Generated by Django 4.1.7 on 2023-11-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_producto_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='libraje',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tamanio',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
