# Generated by Django 4.1 on 2024-05-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_producto_uso_fecha_uso'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto_uso',
            name='condicion',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
