# Generated by Django 4.1.7 on 2023-11-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_producto_area_alter_producto_marca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='resguardo',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
