# Generated by Django 4.1.7 on 2023-11-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_producto_disponible_alter_producto_resguardo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.FloatField(default=0),
        ),
    ]
