# Generated by Django 4.1.7 on 2023-12-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_producto_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='renta',
            name='cantidad',
            field=models.FloatField(default=0),
        ),
    ]
