# Generated by Django 4.1.7 on 2023-12-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_producto_unidad_medida_renta_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.FloatField(default=1),
        ),
    ]
