# Generated by Django 4.1.7 on 2023-12-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_producto_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
